*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../stepDefinition/flutterDev/registration/sd_12_unsuccessful_ActivationOTP_viaEmail.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-27T18:30:49.900775_

*** Test Cases ***
Unsuccessful Activation OTP via Email
    [Tags]    invalid
    [Template]    Scenario Outline Unsuccessful Activation OTP via Email
    7170    kode otp yang anda masukan salah


*** Keywords ***
Background
    Given I was succesfully see OTP verification Form

Scenario Outline Unsuccessful Activation OTP via Email
    [Arguments]    ${otp}    ${err_msg}
    Background
    Given I am on the Input OTP form again
    When I fill in invalid OTP Number "${otp}"
    Then I should see error message notification "${err_msg}"


