*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../stepDefinition/flutterDev/registration/sd_15_confirmation_registrationProcess.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-02-11T16:03:16.945515_

*** Test Cases ***
Confirmation Registration Process
    [Tags]    valid
    Background
    Given the page is showing popup message "Apakah anda yakin telah mengisi data dengan benar"
    When I click button "Ya"
    Then I should see message on Confirmation Form "Pendaftaran Berhasil, Terimakasih sudah melakukan registrasi akun"


*** Keywords ***
Background
    Given I was input valid data until Create Password page, and click "lanjutkan" button


