*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../../platformAndroid/stepDefinition/flutterDev/registration/sd_4_invalid_registerAccount.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-25T00:36:47.785896_

*** Test Cases ***
Invalid Register account
    [Tags]    invalid
    [Template]    Scenario Outline Invalid Register account
    M Tito Ramadhan    titoqa@yopmail.com    ${individual}    Email Sudah Terdaftar
    M Tito Ramadhan    t@mail    ${individual}    Email Tidak Valid


*** Keywords ***
Scenario Outline Invalid Register account
    [Arguments]    ${nama_lengkap}    ${email}    ${tipe_akun}    ${err_msg}
    Given the page is showing Sign Up form
    When I fill in Nama Lengkap "${nama_lengkap}"
    And I fill in Registered Email "${email}"
    And I choose Tipe Akun "${tipe_akun}"
    And I click agree of term of condition
    And I should see activated button "Lanjutkan"
    And I click button "Lanjutkan"
    Then I should see error message notification "${err_msg}"


