*** Settings ***
Documentation    
Test Tags    PilotProject-Login
Resource    ../../stepDefinition/login/sd_25_login_with_valid_credential.resource
Metadata    Feature    Web Login
Metadata    Generated by    _gherkin2robotframework on 2025-02-12T14:46:50.081303_

*** Test Cases ***
Successful login with valid credentials
    [Tags]    valid
    [Template]    Scenario Outline Successful login with valid credentials
    tito136@yopmail.com    P@ssw0rd


*** Keywords ***
Scenario Outline Successful login with valid credentials
    [Arguments]    ${email}    ${password}
    Given the user is on the login page
    When the user enters a valid email, password, and capthca "${email}" "${password}"
    And clicks the login button
    Then the user should be redirected to the Profil Detail's Page
