*** Settings ***
Documentation    
Test Tags    PilotProject-Login
Resource    ../../stepDefinition/login/sd_26_unsucessfull_login_with_invalid_credential.resource
Metadata    Feature    Web Login
Metadata    Generated by    _gherkin2robotframework on 2025-02-15T12:28:37.119117_

*** Test Cases ***
Unsuccessful login with invalid credentials
    [Tags]    valid
    [Template]    Scenario Outline Unsuccessful login with invalid credentials
    ${EMPTY}    P@ssw0rd    email wajib diisi
    titoqa@yopmail.com    p@ssw0rD    password salah
    titoqa@yopmail.com    P@ssw0rd    captcha kosong

*** Keywords ***
Scenario Outline Unsuccessful login with invalid credentials
    [Arguments]    ${email}    ${password}    ${err_msg}
    Given the user is on the login page again
    When the user enters an invalid email, password, and capthca "${email}" "${password}" "${err_msg}"
    And clicks the login button again
    Then the user should see an error message "${err_msg}"
    And the login page should be displayed again


