*** Settings ***
Documentation    
Test Tags    PilotProject-Profile
Resource    ../../stepDefinition/profile/sd_Attempting_to_update_profile_with_invalid_format.resource
Metadata    Feature    Web Profile
Metadata    Generated by    _gherkin2robotframework on 2025-02-20T00:22:12.381317_

*** Test Cases ***
Attempting to update profile with invalid format
    [Tags]    invalid
    [Template]    Scenario Outline Attempting to update profile with invalid format
    ${EMPTY}    ${EMPTY}    field wajib diisi
    mt      ${EMPTY}     field nama lengkap / badan usaha minimal 3 character    
    ${EMPTY}    822134    field nomor telepon minimal 7 character 


*** Keywords ***
Background
    Given the user is logged in

Scenario Outline Attempting to update profile with invalid format
    [Arguments]    ${nama_lengkap}    ${no_tlp}    ${err_msg}    
    Background
    Given the user successfully viewing profile details
    When the user enters an invalid field "${nama_lengkap}" "${no_tlp}"
    And clicks the "Save Changes" button
    Then the user should see an error message "Please enter a valid data" "${err_msg}"
    And the profile page should remain open for the user to correct the information


