*** Settings ***
Documentation    
Test Tags    PilotProject-Profile
Resource    ../../stepDefinition/profile/sd_Canceling_profile_update.resource
Metadata    Feature    Web Profile
Metadata    Generated by    _gherkin2robotframework on 2025-02-19T17:05:46.012126_

*** Test Cases ***
Canceling profile update
    [Tags]    valid
    Background
    Given the user successfully viewing profile details
    When the user clicks the "Cancel" button without making any changes
    Then the user should be redirected back to the previous page
    And no changes should be saved to the profile


*** Keywords ***
Background
    Given the user is logged in


