*** Settings ***
Documentation    
Test Tags    PilotProject-Registration
Resource    ../../stepDefinition/profile/sd_Profile_details_page_is_not_accessible_to_unauthenticated_users.resource
Metadata    Feature    Web Profile
Metadata    Generated by    _gherkin2robotframework on 2025-02-19T10:44:31.852327_

*** Test Cases ***
Profile details page is not accessible to unauthenticated users
    [Tags]    valid
    Background
    Given the user is not logged in
    When the user tries to access the profile details page
    Then the user should be redirected to the login page
    And the user should see a message "Please log in to view your profile"


*** Keywords ***
Background
    Given the user already in login page


