*** Settings ***
Documentation    
Test Tags    PilotProject-Profile
Resource    ../../stepDefinition/profile/sd_Successfully_updating_profile_with_valid_information.resource
Metadata    Feature    Web Profile
Metadata    Generated by    _gherkin2robotframework on 2025-02-19T13:28:40.871381_

*** Test Cases ***
Successfully updating profile with valid information
    [Tags]    valid
    Background
    Given the user successfully viewing profile details
    When the user updates their Nama lengkap/Badan usaha, Daftar sebagai, Kode negara, no tlp, email, kota, kecamatan, and bidang usaha yang diminati
    And clicks the "Save Changes" button
    Then the user should see a success message "Profile updated successfully"
    And the updated information should be displayed on the profile page

*** Keywords ***
Background
    Given the user is logged in


