*** Settings ***
Documentation    
Test Tags    PilotProject-Registration
Resource    ../../stepDefinition/profile/sd_Successfully_viewing_profile_details.resource
Metadata    Feature    Web Profile
Metadata    Generated by    _gherkin2robotframework on 2025-02-18T13:53:21.140531_

*** Test Cases ***
Successfully viewing profile details
    [Tags]    valid
    Background
    Given the user in main page
    And the user navigates to the profile details page
    Then the user should see their details profile
    And the user should see the last updated date of their profile


*** Keywords ***
Background
    Given the user already login with valid data


