*** Settings ***
Metadata    Feature    Open Modal Create Grup
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T13:43:14.497822_

Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_CreateMultiprodukCard.resource


*** Test Cases ***
001 - Open Modal Create Grup
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User click tab Grup Produk
    And User Click button "+ Buat Grup"
    Then Berhasil menampilkan modal Buat Grup

002 - Close Modal Create Grup Dengan Button Batal
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Click Button "Batal" Pada Modal Buat Grup
    Then Modal Buat Grup Tertutup

003 - Close Modal Create Grup Dengan Button X
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Click Button "X" Pada Modal Buat Grup
    Then Modal Buat Grup Tertutup

004 - Field Pilih Produk di Modal Create Grup Menampilkan Produk Dari Katalog Produk Saya
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    Then Modal Menampilkan Produk Dari Katalog Produk Saya

005 - Field Pilih Produk di modal Create Grup ketika produk sudah ditambahkan di "Produk Saya",dihapus dari "Produk Saya"
    [Tags]    negativecase
    Background
    Given User berada pada halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    And Modal Menampilkan List Produk Dari Katalog Produk Saya
    And User Click Button "Batal" Pada Modal Buat Grup
    And User Click Tab Produk Saya
    And User Menghapus Produk Yang Sudah Ditambahkan
    And User Click Tab Grup Produk
    And User Click Button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    Then Modal Menampilkan Produk Dari Katalog Produk Saya yang sudah dihapus dari "Produk Saya"

006 - Field Pilih Produk di modal Create Grup ketika produk sudah ditambahkan di "Produk Saya" tetapi dihapus dari Daftar Produk Chatshop
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    And Modal Menampilkan List Produk Dari Katalog Produk Saya
    And User Click Button "Batal" Pada Modal Buat Grup
    And Merchant Menghapus Salah Satu Produk Yang Sudah Ditambahkan
    And User Click button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    Then Modal Menampilkan Produk Dari Katalog Produk Saya yang sudah dihapus dari "Produk Saya"
    And Produk yang dihapus tetap muncul

007 - Field Pilih Produk ketika stock produk out of stock
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click button "+ Buat Grup"
    And User Scroll Modal Sampai Field Pilih Produk
    And User Coba Click Produk Stok Habis
    Then Produk Pada Modal Tidak Ter-Checklist

008 - Create Grup dari link 'Buat Grup' di bawah wording 'Tidak ada grup produk'
    [Tags]    positivecase
    Background
    Given User berada pada halaman Group Produk kosong
    When User click label link 'Buat Grup' pada section dibawah 'Tidak ada grup produk'
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User pilih produk
    And User click 'Buat Grup' Button
    Then User Berhasil create Grup

009 - Create Grup dari link '+ Buat Grup' button
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User pilih produk
    And User click 'Buat Grup' Button
    Then User Berhasil create Grup

010 - Create Grup tanpa input Deskripsi
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User Mengosongkan Field Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Berhasil create Grup Tanpa Deskripsi

011 - Create Grup dengan nama Grup yang sudah tersimpan di Grup Produk
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup dengan nama yang sudah ada
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User pilih produk
    And User click 'Buat Grup' Button
    Then User berhasil simpan dengan nama yang sudah ada

012 - Create Grup tanpa input Nama Grup
    [Tags]    negativecacse
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Mengosongkan Field Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Gagal create Grup dan muncul error "Nama grup wajib diisi" dibawah field Nama Grup

013 - Create Grup dengan input Nama Grup kurang dari 3 karakter
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Input Nama Grup Kurang Dari 3 Karakter
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Gagal Create Grup dan Muncul Error "Nama grup harus terdiri dari 3-100 karakter" Dibawah Field Nama Grup

014 - Create Grup dengan input Nama Grup lebih dari 100 karakter
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Input Nama Grup Lebih Dari 100 Karakter
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Gagal create Grup dan muncul error "Nama grup harus terdiri dari 3-100 karakter" dibawah field Nama Grup

015 - Create Grup tanpa "Pilih Produk"
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Terapkan Banner
    And User Mengosongkan Field Pilih Produk
    And User click 'Buat Grup' Button
    Then User Gagal Create Grup dan Muncul Error "Produk wajib dipilih" Dibawah Field Pilih Produk

016 - Grup Produk auto remove produk ketika produk yang digunakan dihapus semua dari daftar 'Produk Saya'
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Tab Produk Saya
    And User Menghapus Semua Produk Yang Telah Ditambahkan Ke Grup
    And User Click Tab Grup Produk
    Then User Melihat Card Grup Produk Tidak Menampilkan Produk

017 - Grup Produk auto remove produk ketika produk yang digunakan dihapus sebagian dari daftar 'Produk Saya'
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Tab Produk Saya
    And User Menghapus Sebagian Produk Yang Telah Ditambahkan Ke Grup
    And User Click Tab Grup Produk
    Then User Melihat Card Grup Produk Tidak Menampilkan Produk Yang Telah Dihapus
    
#--Sudah tercoverage dengan Scenario 006 (Terdapat ubahan flow juga utk tidak dapat menghapus produk di merchant dashboard ketika produk dipakai oleh affiliate)--#
# 018 - Grup Produk auto remove produk ketika produk yang digunakan dihapus semua dari CMS Merchant (Chatshop)
#     [Tags]    negativecase
#     Background
#     Given User Berada Pada Halaman Group Produk
#     When User Click Tab Produk Saya
#     And User Check Produk Yang Ada di Grup
#     And User Click Tab Grup Produk
#     And Merchant Menghapus Produk Semua Yang Ada di Grup
#     And User Refresh Page
#     Then User Melihat Card Grup Produk Menampilkan Produk Kosong

# 019 - Grup Produk auto remove produk ketika produk yang digunakan dihapus Sebagian dari CMS Merchant (Chatshop)
#     [Tags]    negativecase
#     Background
#     Given User Berada Pada Halaman Group Produk
#     When User Click Tab Produk Saya
#     And User Check Produk Yang Ada di Grup
#     And User Click Tab Grup Produk
#     And Merchant Menghapus Sebagian Produk Yang Ada di Grup
#     And User Refresh Page
#     Then User Melihat Card Grup Produk Tidak Menampilkan Produk Yang Dihapus

020 - Search Produk di Pop Up Create Grup
    [Tags]    postivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Click Field Search Produk
    And User Input Nama Produk Yang Ingin Dicari
    Then List Produk Menampilkan Produk Sesuai Dengan Keyword Pencarian

021 - Search Produk di pop up Create Grup dengan invalid nama produk
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Click Field Search Produk
    And User Input Nama Produk Yang Invalid
    Then List Produk Menampilkan "Produk tidak ditemukan."

022 - User dapat adjust banner di field Banner
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Menyesuaikan Banner Sesuai Keinginan
    And User Terapkan Banner
    Then User Berhasil Menyesuaikan Banner

023 - User batal menambahkan banner di pop up Buat Grup
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Menyesuaikan Banner Sesuai Keinginan
    And User Click Button "Batal"
    Then User Berhasil batal menambahkan banner

024 - User mengganti file banner yang sudah ditambahkan di Pop Up Buat Grup
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Menyesuaikan Banner Sesuai Keinginan
    And User Terapkan Banner
    And User Hover Field Banner
    And User Upload File Banner Kedua
    Then User berhasil mengganti file banner dengan file yang baru di Pop Up Buat Grup

025 - User remove file banner yang sudah ditambahkan
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Terapkan Banner
    And User Hover Field Banner
    And User Click Icon "x"
    Then User Berhasil Menghapus Banner

026 - User Batal mengganti file banner yang sudah ditambahkan di Pop up Buat Grup
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Terapkan Banner
    And User Upload File Banner Baru
    And User Click Button "Batal"
    Then Field Banner Menampilkan Banner Yang Diupload Sebelumnya

027 - User dapat menyesuaikan file banner yang sudah ditambahkan di Pop up Buat Grup
    [Tags]    posivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User Scroll Down Sampai Field Banner
    And User Upload File Banner
    And User Terapkan Banner
    And User Hover Field Banner
    And User Click Button "Sesuaikan"
    And User Menyesuaikan Banner Sesuai Keinginan
    And User Terapkan Banner
    Then User Berhasil Menyesuaikan Banner

028 - Buat Grup Produk dengan tanpa input banner
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Berhasil Create Grup Tanpa Banner

029 - Buat Grup Produk dengan file banner valid
    [Tags]    positivecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Menyesuaikan Banner Sesuai Keinginan
    And User Terapkan Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Berhasil Create Grup Dengan Banner

030 - Buat Grup Produk dengan file banner valid sebelum click Terapkan
    [Tags]    negativecase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner
    And User Pilih Produk
    And User click 'Buat Grup' Button
    Then User Gagal create Grup dan muncul error "Silahkan batalkan atau terapkan gambar"

031 - Buat Grup Produk dengan file banner di atas 5MB
    [Tags]    negativeCase
    Background
    Given User Berada Pada Halaman Group Produk
    When User Click Button "+ Buat Grup"
    And User input Nama Grup
    And User input Deskripsi
    And User Upload File Banner diatas 5MB
    Then User Gagal Upload Banner dan Muncul Error "Ukuran file maks. 5MB"

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
    Then User berhasil login dan diarahkan ke halaman Dashboard Affiliator
