*** Settings ***
Metadata    Feature    Delete Grup Produk Normal Flow
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T13:43:14.497822_


Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_DeleteMultiprodukCard.resource


*** Test Cases ***
001 - Delete Grup Produk Normal Flow
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    Then Cek dan hapus grup produk jika tersedia

002 - Delete Grup Produk kondisi daftar produk kosong
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    Then Cek dan hapus grup produk jika tersedia

003 - Data tidak terhapus ketika batal Delete Grup Produk dengan click button Batal
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    Then User Click Button "Batal" Card Delete

004 - Data tidak terhapus ketika batal Delete Grup Produk dengan click button X
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    Then User Click Button "X" Card Delete

005 - Delete Grup pada Page kedua
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click page navigation page 2
    Then Cek dan hapus grup produk page 2 jika tersedia


*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
    Then User berada di halaman Dashboard Affiliator


