*** Settings ***
Documentation    
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_listCollection-Card-Produk.resource
Metadata    Feature    Group Produk Empty
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T10:35:33.235750_

*** Test Cases ***
001 - Open Group Produk ketika belum ada 'Grup Produk'
    [Tags]    negativeCase
    Background
    Given User berada pada halaman Dashboard
    And User klik tombol menu "Produk"
    When User pindah ke navigasi menu "Group Produk"
    Then User berhasil melihat halaman Group Produk kosong

002 - Menampilkan Group produk yang sudah terbuat
    [Tags]    positiveCase
    Background
    Given User sudah di halaman Group Produk
    When User view Group produk card
    Then Sistem menampilkan data setiap card produk dengan detail informasi "Nama card", "deskripsi singkat card", "jumlah product yang ada dalam card", "button share", "button edit", "icon delete"
    And Fungsi pagination berjalan dengan baik 

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    And User input form login dengan data valid
    And User berhasil login dan diarahkan ke halaman Dashboard Affiliator