*** Settings ***
Documentation    
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_NotifikasiAffiliateWhatsapp_step_definitions.resource
Metadata    Feature    Notifikasi Affiliate Whatsapp
Metadata    Generated by    _gherkin2robotframework on 2026-07-27T11:37:30.223439_

*** Test Cases ***
001 - Transaksi beberapa merchant Biteship Otomatis
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And Tambah Produk Otomatis Kedua
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user isi form Informasi Pengiriman pilih jasa pengiriman kedua
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    Then User Check Notifikasi Pesanan Di Whatsapp

002 - Transaksi satu merchant Biteship Otomatis
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    Then User Check Notifikasi Pesanan Di Whatsapp

003 - Transaksi beberapa merchant Biteship Manual
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And Tambah Produk Otomatis Kedua
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user isi form Informasi Pengiriman pilih jasa pengiriman kedua
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And User Check Notifikasi Pesanan Di Whatsapp
    Then Merchant Cek Pesanan

004 - Transaksi satu merchant Biteship Manual
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And User Check Notifikasi Pesanan Di Whatsapp
    Then Merchant Cek Pesanan

005 - Notifikasi Resi Owner diterima owner (merchant) ketika transaksi sudah dibayar dengan kondisi setup pengiriman biteship manual
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And Merchant Proses Pesanan
    And Merchant Ubah Pesanan Ke Siap Diambil
    And Merchant Klik Button Cetak Resi Pada Detail Pesanan di Page Siap Diambil
    Then Merchant Cek Notifikasi Resi Di Whatsapp

006 - Notifikasi Resi Owner diterima owner (merchant) ketika transaksi sudah dibayar dengan kondisi setup pengiriman biteship otomatis
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And Merchant Klik Button Cetak Resi Pada Detail Pesanan di Page Siap Diambil Merchant Biteship Otomatis
    Then Merchant Cek Notifikasi Resi Di Whatsapp

007 - Notifikasi Resi Owner tidak diterima owner (merchant) ketika transaksi sudah dibayar dengan kondisi setup pengiriman biteship manual
    [Tags]    negativeCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And Merchant Proses Pesanan
    And Merchant Ubah Pesanan Ke Siap Diambil
    And Merchant Klik Button Cetak Resi Pada Detail Pesanan di Page Siap Diambil
    Then Merchant Tidak Menerima Notifikasi Resi Di Whatsapp

008 - Notifikasi Resi Owner tidak diterima owner (merchant) ketika transaksi sudah dibayar dengan kondisi setup pengiriman biteship otomatis
    [Tags]    negativeCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    And User diarahkan ke halaman Pembayaran Berhasil
    And Merchant Klik Button Cetak Resi Pada Detail Pesanan di Page Siap Diambil Merchant Biteship Otomatis
    Then Merchant Tidak Menerima Notifikasi Resi Di Whatsapp

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    And User input form login dengan data valid
    And User berhasil login dan diarahkan ke halaman Dashboard Affiliator


