*** Settings ***
Documentation    
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_Payment_step_definitions.resource
Metadata    Feature    Payment
Metadata    Generated by    _gherkin2robotframework on 2026-07-21T11:48:53.935825_

*** Test Cases ***
001 - Akses halaman Detail Pesanan & Total Pembayaran - Transaksi produk Non Varian only & Delivery Manual
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    Then User diarahkan ke halaman Detail Pesanan & Total Pembayaran

002 - Akses halaman Detail Pesanan & Total Pembayaran - Transaksi produk Varian only & Delivery Manual
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    Then User diarahkan ke halaman Detail Pesanan & Total Pembayaran

003 - Akses halaman Detail Pesanan & Total Pembayaran - Transaksi produk Non Varian only & Delivery Otomatis
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    Then User diarahkan ke halaman Detail Pesanan & Total Pembayaran Merchant Delivery Otomatis


004 - Akses halaman Detail Pesanan & Total Pembayaran - Transaksi produk Varian only & Delivery Otomatis
    [Tags]    positiveCase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    Then User diarahkan ke halaman Detail Pesanan & Total Pembayaran Merchant Delivery Otomatis

007 - Kembali ke Toko - dari halaman Detail Pesanan & Bayar Sekarang
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Kembali Ke Toko
    And User Click "Ya, Kembali" Pada popUp Konfirmasi Kembali Ke Toko
    Then User diarahkan ke halaman Dashboard Grup Produk Affiliator

008 - Akses halaman 'Payment Method' melalui button Lanjut Pembayaran 
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    Then User diarahkan ke halaman Payment Method Xendit 

009 - Pembayaran dengan salah satu bank
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Bank Transfer
    And User Pilih Salah Satu Bank
    And User Melakukan Pembayaran
    Then User Diarahkan Ke Halaman Pembayaran Berhasil

010 - Pembayaran dengan QRIS
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Pembayaran QRIS
    And User Scan QRIS
    Then User Berhasil Scan QR Dan Diarahkan Ke Halaman Pembayaran Berhasil

011 - Pembayaran Ketika Expired
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Varian Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And User Click Button Buat Pesanan
    And User Click Lanjut Pada Popup Konfirmasi Pesanan
    And User diarahkan ke halaman Detail Pesanan & Total Pembayaran
    And User Click Lanjut Pembayaran
    And User diarahkan ke halaman Payment Method Xendit 
    And User Pilih Salah Satu Bank
    Then User Melakukan Pembayaran Ketika Expired

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
    Then User berada di halaman Dashboard Affiliator


