*** Settings ***
Metadata    Feature    Share Page
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T13:43:14.497822_
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_SharePage.resource
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_ShareModalCard.resource
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_PlaceAndCreateOrder.resource

*** Test Cases ***
#    Beberapa step definition diambil dari shared modal card karena memang flownya sama
001 - User Akses halaman 'Informasi Pengiriman'
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    # And cek apakah ada button detail di button detail
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    Then user verify halaman checkout sesuai dengan card yang dishare
    And user verify halaman informasi pengiriman sesuai dengan card yang dishare
   


002 - User Akses halaman 'Informasi Pengiriman'
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    # And cek apakah ada button detail di button detail
     And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user click button kembali dari halaman informasi pengiriman
    Then user verify berada di halaman list produk

    
003 - Checkout hanya produk Non Varian melalui List Produk dengan pengiriman Delivery Manual - Modal Checkout
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And User click button lanjut pembayaran
    And Admin login ke cms Merchant
    Then Admin verifikasi data masuk ke cms fitur penjualan retail tab pending

004 - Checkout produk terdapat Varian melalui List Produk dengan pengiriman Delivery Manual - Modal Checkout
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk varian, 
# tidak boleh ada produk yang non-varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And User click button lanjut pembayaran
    And Admin login ke cms Merchant
    Then Admin verifikasi data masuk ke cms fitur penjualan retail tab pending

005 - Checkout hanya produk Non Varian melalui List Produk dengan pengiriman Delivery Otomatis - Modal Checkout
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And User click button lanjut pembayaran
    And Admin login ke cms Merchant
    Then Admin verifikasi data masuk ke cms fitur penjualan retail tab pending

006 - Checkout produk terdapat Varian melalui List Produk dengan pengiriman Delivery Otomatis - Modal Checkout
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And User click button lanjut pembayaran
    And Admin login ke cms Merchant
    Then Admin verifikasi data masuk ke cms fitur penjualan retail tab pending

007 - User Buat Pesanan dengan pengiriman Delivery kemudian lanjut checkout dengan kondisi produk berubah menjadi out of stock
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    # And user click button + di List Produk
    # And user klik tambah + di List Produk -2
    # And user tambah item sebanyak-banyaknya ke keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user klik tambah + di List Produk produk urutan ke-3
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    # And user klik button buat pesanan
    # And user klik pop up konfirmasi pesanan
    # And user verifkasi halaman menunggu pembayaran
    And Admin login ke cms Merchant
    And Admin verifikasi stok barang kosong atau tidak tersedia
    And Switch Window    ${share_handle}
    # And user verifikasi ada di halaman checkout setelah switch window
    Then user verifikasi di page affilaite bahwa ada popup stok kosong pada produk yang sedang dipesan

008 - User mengosongkan semua field pada halaman Informasi Pengiriman metode Delivery
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user klik button buat pesanan
    Then User Verify Error Semua Kosong

009 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan field 'Nama Lengkap Penerima'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    Then User Verify Error Nama Kosong

010 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan field 'Nomor Whatsapp Aktif'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    Then User Verify Error WA Kosong

011 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan field 'Kecamatan / Kota / Provinsi / Kode Pos'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman Detail Alamat
    And user klik button buat pesanan
    Then User Verify Error kecamatan / kota / provinsi / kode pos Kosong

012 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan field 'Detail Alamat (Jalan, RT/RW, dll.) *'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user klik button buat pesanan
    Then User Verify Error detail alamat rt rw Kosong


013 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan semua field 'Pilih Pengiriman'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    Then User Verify Error detail pengiriman Kosong

014 - User Buat Pesanan dengan pengiriman Delivery dan mengisi Informasi Pengiriman dengan mengosongkan salah satu field 'Pilih Pengiriman'
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    Then User Verify Error detail pengiriman Kosong

015 - Input Nomor WhatsApp dengan selain angka (special character, huruf)
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp dengan spesial character
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user klik button buat pesanan
    Then User Verify Error detail pengiriman no whatsapp dengan spesial character

016 - Hapus sebagian produk non varian pada Daftar Paket Pesanan
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
# test case yang berhasil nambah banyak item ke keranjang
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user click button + di List Produk
    And user click button close di modal pop-up keranjang
    And user klik tambah + di List Produk -2
    And user click button close di modal pop-up keranjang
    And user klik tambah + di List Produk produk urutan ke-2
    And user click button close di modal pop-up keranjang
    # And user klik tambah + di List Produk produk urutan ke-3
    And user click menu fitur keranjang di halaman produk affiliate
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga sebelum di delete produk
    And user click button delete pada halaman informasi pengiriman untuk menghapus produk yang sudah ditambahkan ke keranjang
    Then user cek total harga setelah delete produk

017 - Hapus sebagian produk varian pada Daftar Paket Pesanan
# Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
# test case yang berhasil nambah banyak item ke keranjang
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user click button + di List Produk
    And user click button close di modal pop-up keranjang
    And user klik tambah + di List Produk -2
    And user click button close modal pop-up varian
    And user klik tambah + di List Produk produk urutan ke-2
    And user click button tambah ke pesanan untuk produk varian
    And user click button close di modal pop-up keranjang
    # And user klik tambah + di List Produk -2
    # And user klik tambah + di List Produk produk urutan ke-3
    # And user click button tambah ke pesanan untuk produk varian
    And user click menu fitur keranjang di halaman produk affiliate
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga sebelum di delete produk
    And user click button delete pada halaman informasi pengiriman untuk menghapus produk yang sudah ditambahkan ke keranjang
    Then user cek total harga setelah delete produk

018 - Hapus semua produk di salah satu merchant pada Daftar Paket Pesanan
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And Tambah Produk Otomatis Kedua
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga setelah delete produk
    And User Hapus Semua Produk Di Salah Satu Merchant
    Then user cek total harga setelah delete produk

019 - Hapus semua produk di semua merchant pada Daftar Paket Pesanan
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And Tambah Produk Otomatis Kedua
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga setelah delete produk
    And User Hapus Semua Produk Di Semua Merchant
    Then user cek total harga setelah delete produk

032 - User Isi Informasi Pengiriman dengan benar kemudian ganti Pilihan Kurir Pengiriman 
     
    # Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
# test case yang berhasil nambah banyak item ke keranjang
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user click button + di List Produk
    # And user click button close di modal pop-up keranjang
    # And user klik tambah + di List Produk -2
    # And user click button close di modal pop-up keranjang
    # And user klik tambah + di List Produk produk urutan ke-2
    # And user click button close di modal pop-up keranjang
    # # And user klik tambah + di List Produk produk urutan ke-3
    # And user click menu fitur keranjang di halaman produk affiliate
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga sebelum di delete produk
    And user ganti jasa pengiriman di halaman informasi pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And User click button lanjut pembayaran
    And Admin login ke cms Merchant
    And Switch Window    ${cms_handle}
    Then Admin verifikasi data masuk ke cms fitur penjualan retail tab pending
    # And user click button delete pada halaman informasi pengiriman untuk menghapus produk yang sudah ditambahkan ke keranjang
    # Then user cek total harga setelah delete produk


 033 - Kembali ke Toko Setelah checkout
    # Note, untuk test case ini hanya bisa digunakan pada card yang hanya memiliki produk non-varian aja,
# tidak boleh ada produk yang varian
# cardnya harus no 1 atau paling terbaru
# test case yang berhasil nambah banyak item ke keranjang
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And Tambah Produk Otomatis
    And user click button + di List Produk
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user isi form Informasi Pengiriman nama lengkap
    And user isi form Informasi Pengiriman no whatsapp
    And user isi form Informasi Pengiriman kecamatan / kota / provinsi / kode pos
    And user isi form Informasi Pengiriman Detail Alamat
    And user isi form Informasi Pengiriman pilih jasa pengiriman
    And user cek total harga sebelum di delete produk
    And user ganti jasa pengiriman di halaman informasi pengiriman
    And user klik button buat pesanan
    And user klik pop up konfirmasi pesanan
    And user verifkasi halaman menunggu pembayaran
    And user click button kembali ke toko
    And user click button konfirmasi ya, kembali
    Then user verify ada di halaman koleksi produk
   
  
  

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
   
Admin login ke cms Merchant
    Given Open Chrome With Notification Blocked
    When Open Browser Staging Merchant
    Then Valid Login Merchant
    And User berada di dashboard staging merchant 
    And Click modalPopUP dashboard-merchant untuk complete profile
    And Click switch user cms merchant

Admin verifikasi data masuk ke cms fitur penjualan retail tab pending
     Given User click menu Penjualan Retail
     When User click tab pending
     And User cari nama_pembeli di tab pending
     And User click button detail user di tab pending
     Then User verify Detail Order

Admin verifikasi stok barang kosong atau tidak tersedia
    Given user click menu produk merchant cms
    when user click sub menu daftar produk
    And user cari barang yang sedang dipesan di page affiliate
    And user edit produk dan buat stok jadi tidak tersedia
    Then Switch Browser    1