*** Settings ***
Metadata    Feature    Share Modal Card Mobile Flow
Metadata    Generated by    _gherkin2robotframework on 2026-04-20
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_ShareModalCardMobile.resource


*** Test Cases ***
007 - User click 'Bagikan ke Whatsapp' di Mobile device kondisi sudah login whatsapp app
    Background Mobile
    Given User Click Menu Produk Mobile
    When User Click Tab Grup Produk Mobile
    And User Click Button Bagikan Pada Card Grup Produk Mobile
    And User Click Button Bagikan ke Whatsapp Mobile
    And Direct ke aplikasi whatsapp
    And User Pilih Kontak Yang Akan Dikirimi Pesan
    And User Click Button Kirim Pada Aplikasi Whatsapp
    Then Berhasil Share Grup Produk Ke Whatsapp Mobile

008 - User click 'Bagikan ke Whatsapp' di Mobile device kondisi whatsapp app tidak terinstall
    Background Mobile
    Given User Click Menu Produk Mobile
    When User Click Tab Grup Produk Mobile
    And User Click Button Bagikan Pada Card Grup Produk Mobile
    And User Click Button Bagikan ke Whatsapp Mobile
    Then Direct ke halaman api.whatsapp.com untuk mengunduh aplikasi whatsapp

009 - Akses share link dengan Scan Kode QR di Pop Up 'Bagikan Grup Produk'
    [Tags]    positivecase
    Background Mobile
    Given User Click Menu Produk Mobile
    When User Click Tab Grup Produk Mobile
    And User Click Button Bagikan Pada Card Grup Produk Mobile
    And User Scan Kode QR di Pop Up 'Bagikan Grup Produk' Mobile
    Then Berhasil Scan Kode QR dan diarahkan ke halaman grup produk yang sudah di share

*** Keywords ***
Background Mobile
    Given User telah membuka website pagii affiliate Mobile
    When User input form login dengan data valid mobile
    Then User berada di halaman Dashboard Affiliator Mobile
    