*** Settings ***
Metadata    Feature    Share Page
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T13:43:14.497822_


Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_CreateMultiprodukCard.resource
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_SharePage.resource
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_ShareModalCard.resource





*** Test Cases ***

    
#    Beberapa step definition diambil dari shared modal card karena memang flownya sama
#  
001 - Akses halaman list produk grup dengan kondisi tanpa Banner
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And user buka page di url hasil copy share url
    Then user verify halaman produk sesuai dengan card yang dishare
    
    # Then User melihat halaman produk sesuai dengan card yang dishare

002 - Akses halaman list produk grup dengan kondisi dengan Banner
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk dengan banner
    And Verify Copy Share URL
    And Verify Share URL Product
    And user buka page di url hasil copy share url
    Then user verify halaman produk sesuai dengan card yang dishare

003 - User membuka Detail Produk Non Varian melalui button [Detail]
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    Then user verify halaman produk sesuai dengan card yang dishare

004 - User membuka Detail Produk Varian melalui button [Detail & Varian]
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk dengan banner
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail dan varian di button detail
    Then user verify halaman produk sesuai dengan card yang dishare

005 - Lihat selengkapnya pada detail produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    Then user click button lihat selengkapnya di card produk

006 - Add Produk melalui button + di List Produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    And user click button + di List Produk
    Then user verify halaman checkout sesuai dengan card yang dishare

007 - Add Produk melalui button Tambah Pesanan di pop up detail produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    And user click button Tambah ke Pesanan
    Then user verify pop up halaman checkout / keranjang sudah muncul

008 - Edit Added produk pesanan dari Detail Produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    # And user click button + di List Produk
    And user klik tambah + di List Produk -2
    And user klik tambah produk
    Then user klik delete produk

009 - Add Produk kondisi out of stock dari list produk dan detail produk
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user klik button edit
    And cari data di list yang out of stock
    And user klik button x di form edit
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    Then verify produk yang out of stock tidak muncul di halaman produk yang dishare

010 - Add Varian Produk kondisi Varian tersebut out of stock
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user klik button edit
    And cari data di list yang out of stock
    And user klik button x di form edit
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    Then verify produk yang out of stock tidak muncul di halaman produk yang dishare

011 - User dapat close detail produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    And user click button close di pop up detail produk
    Then back to halaman produk sesuai dengan card yang dishare

012 - Remove added Produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    # And user click button + di List Produk
    And user klik tambah + di List Produk -2
    And user klik tambah produk
    And user klik delete produk sampai habis
    Then Keranjang menjadi kosong

    
013 - Kembali ke halaman List Produk dari Informasi Pengiriman
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk    
    And User Click tab Grup Produk 
    And cek nama card di share modal
    And user click button "Bagikan" Card Produk
    And Verify Copy Share URL
    And Verify Share URL Product
    And cek apakah ada button detail di button detail
    # And user click button + di List Produk
    And user klik tambah + di List Produk -2
    And user klik tambah produk
    And user klik button chekout sekarang
    And user verify halaman informasi pengiriman
    And user click button kembali dari halaman informasi pengiriman
    Then user verify berada di halaman list produk

    


*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
    Then User berada di halaman Dashboard Affiliator