*** Settings ***
Metadata    Feature    Share Modal Card Flow
Metadata    Generated by    _gherkin2robotframework on 2026-04-20T13:43:14.497822_
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_CreateMultiprodukCard.resource
Resource    ../../../stepDefinition/dashboard-affiliate/multiproduk/sd_ShareModalCard.resource


*** Test Cases ***
001 - User akses pop up Bagikan Grup Produk
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    Then User Click Button "Bagikan" Pada Card Produk

002 - Salin 'Tautan Berbagi Koleksi Grup Produk'
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL
    Then Verify Share URL Product

# 003 di drop dari tim development

004 - User click 'Bagikan ke Whatsapp' kondisi sudah login whatsapp web
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And user click button "Bagikan" Pada Card Produk
    And user click button Bagikan ke Whatsapp
    And Verify Copy Share URL for whatsapp
    And user buka Whatsapp Web
    And user pilih kontak whatsapp yang akan dikirimi pesan
    And user paste dan kirim share URL di kolom chat whatsapp
    Then Verify Share URL terkirim di whatsapp

005 - User click 'Bagikan ke Whatsapp' kondisi belum login whatsapp web
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And user click button "Bagikan" Pada Card Produk
    And user click button Bagikan ke Whatsapp
    Then Open Whatsapp In New Tab

006 - User click 'Bagikan ke Whatsapp' di kondisi belum login whatsapp app
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And user click button "Bagikan" Pada Card Produk
    And user click button Bagikan ke Whatsapp
    Then Open Whatsapp Application

010 - Unduh QR Code
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And user unduh QR Code
    Then Verify QR Code Downloaded

011 - Akses share link dengan Scan Kode QR yang baru di-download
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And user unduh QR Code
    Then Verify And Open QR Downloaded

#  untuk step open new tab with share url, cek wifi icon kalo sudah mati, langsung di enter manual di ULR address (yang sudah terisi url yang sudah di copy)

012 - User Bagikan Grup Produk ketika disconnected internet
    [Tags]    negativecase
    [Teardown]    Enable Internet
    Background

    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And Verify Copy Share URL wifi mati
    And open new tab with share URL
    And Disable Internet
    Then Verify page not found

013 - User akses pop up Bagikan Grup Produk pada grup dengan produk 0
    [Tags]    negativecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And user click button "Bagikan" Card Produk pada grup dengan produk 0
    Then Verify berisi 0 produk

014 - Close pop up "Bagikan Grup Produk" dengan button x
    [Tags]    positivecase
    Background
    Given User berada di halaman Dashboard Affiliator
    When User Click menu Produk
    And User Click tab Grup Produk
    And User Click Button "Bagikan" Pada Card Produk
    And User Click Button close pop up "Bagikan Grup Produk"
    Then page kembali ke dashboard setelah pop up ditutup

nyalakan internet
    Given Enable Internet


*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    When User input form login dengan data valid
    Then User berada di halaman Dashboard Affiliator
