*** Settings ***
Documentation    
Test Tags    PilotProject-Registration
Resource    ../../../pilotprojectWebsite/stepDefinition/registration/sd_16_successful_ActivationOTP_viaEmail.resource
Metadata    Feature    Web Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-29T23:00:10.422994_
Test Setup    Connect To Gherkin API DB

*** Test Cases ***
Successful activation OTP
    [Tags]    valid
    Background
    Given Page is redirect and I am already in OTP page
    When i fill the otp page with right otp
    And I click "Verifikasi OTP" button
    Then I can see notification Registrasi anda berhasil


*** Keywords ***
Background
    Given I was input valid data on registration form and click button "Ok" in popup confirmation

