*** Settings ***
Documentation    
Test Tags    PilotProject-Registration
Resource    ../../../pilotprojectWebsite/stepDefinition/registration/sd_17_unsuccesful_activationOTP_viaEmail.resource
Metadata    Feature    Web Registration
Metadata    Generated by    _gherkin2robotframework on 2025-02-01T23:16:22.258996_

*** Test Cases ***
Unsuccesfull activation OTP
    [Tags]    valid
    [Template]    Scenario Outline Unsuccesfull activation OTP
    7170    OTP yang anda inputkan salah

*** Keywords ***
Background
    Given I was input valid data on registration form, and click button "Ok" in popup confirmation

Scenario Outline Unsuccesfull activation OTP
    [Arguments]    ${otp}    ${err_msg}
    Background
    Given Page is redirect and I am already in OTP page for testing invalid
    When i fill the otp page with wrong number "${otp}"
    And I click "Verifikasi OTP" button for testing invalid
    Then I should see error message notification "${err_msg}"


