*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2024-12-27T20:31:56.773063_
Library    Collections
Library    SeleniumLibrary

*** Keywords ***
User berada dihalaman login TM Digital
    Open Browser    https://wgs:25K9v47BU52NpegG@tmdigital.stagingapps.net/login    chrome
    Maximize Browser Window

User input alamat email "${email}"
    Input Text    (//input[contains(@class,'form-control form-control-user')])[1]    ${email} 

User input password "${password}"
    Input Password    (//input[contains(@class,'form-control form-control-user')])[2]    ${password}

User klik button "Sign In"
    Click Button    //button[contains(@class,'btn btn-primary')]

User sukses melakukan login dengan redirect ke halaman dashboard TM Digital
    Wait Until Element Is Visible    //span[contains(@class,'text-bold text')]
    Sleep    3s
    Close Browser

#-----------LOGIN FOR GLOBAL VARIABLE----------------#
User already logged in to TM Digital
    User berada dihalaman login TM Digital
    Input Text    (//input[contains(@class,'form-control form-control-user')])[1]    titoqa@maildrop.cc
    Input Password    (//input[contains(@class,'form-control form-control-user')])[2]    P@ssw0rd
    User klik button "Sign In"
    Wait Until Element Is Visible    //span[contains(@class,'text-bold text')]

