*** Settings ***
Force Tags    MelawaiApps
Resource    .../../../../platformAndroid/stepDefinition/sd_loginUser.robot
Resource    ../../platformAndroid/stepDefinition/sd_openApps.robot
Metadata    Feature    MelawaiApps Login
Metadata    Generated by    _gherkin2robotframework on 2025-01-01T23:47:35.220325_

*** Test Cases ***
Melakukan login dengan data valid
    [Tags]    valid
    [Template]    Scenario Outline Melakukan login dengan data valid
    titoqa@maildrop.cc    P@ssw0rd
    081573313196    P@ssw0rd

*** Keywords ***
Background
    [Documentation]    User sudah membuka aplikasi melawai kemudian tap button masuk
    Given User membuka aplikasi melawai
    And User tap button masuk

Scenario Outline Melakukan login dengan data valid
    [Arguments]    ${username}    ${password}
    Background
    Given User berada pada halaman login
    When User input nomor telepon atau email "${username}"
    And User input kata sandi "${password}"
    And User tap button masuk di halaman login
    Then User masuk ke homepage aplikasi melawai 
    And User dapat melihat halaman profile


