*** Settings ***
Force Tags    MelawaiApps
Resource    ../../platformAndroid/stepDefinition/sd_openApps.robot
Metadata    Feature    MelawaiApps Splash Screen
Metadata    Generated by    _gherkin2robotframework on 2024-12-28T17:55:15.083527_

*** Test Cases ***
Membuka Aplikasi Melawai
    [Tags]    valid
    Given User berada pada home device
    When User tap icon melawai aplikasi
    Then Aplikasi melawai sukses terbuka


