*** Settings ***
Force Tags    MelawaiApps
Resource    ../../platformAndroid/stepDefinition/sd_registerUser.robot
Resource    ../../platformAndroid/stepDefinition/sd_openApps.robot
Metadata    Feature    MelawaiApps Register
Metadata    Generated by    _gherkin2robotframework on 2025-01-03T23:32:19.348061_

*** Test Cases ***
Melakukan register dengan data valid example line 30
    [Tags]    valid
    [Template]    Scenario Outline Melakukan register dengan data valid
    6282214634090   titotest96@mail.com    P@ssw0rd    Bandung Indo    M Tito Ramadhan        


*** Keywords ***
Background
    [Documentation]    User sudah membuka aplikasi melawai
    Given User membuka aplikasi melawai

Scenario Outline Melakukan register dengan data valid
    [Arguments]    ${telepon}    ${email}    ${password}    ${alamat}    ${nama_lengkap}    
    Background
    Given User berada pada halaman daftar akun Optik Melawai
    When User input field nomor telepon "${telepon}"
    And User tekan button "lanjutkan"
    And User input field OTP validasi Nomor Telepon
    # And User tekan button "selesai dan lanjutkan"
    # And User input field alamat email "${email}"
    # And User tekan kembali button "lanjutkan"
    # And User input field OTP validasi Alamat Email
    # And User tekan kembali button "selesai dan lanjutkan"
    # And User input field kata sandi "${password}"
    # And User input field alamat "${alamat}"
    # And User pilih dropdown Provinsi
    # And User pilih dropdown Kota
    # And User pilih dropdown Titel
    # And User input field Nama Lengkap "${nama_lengkap}"
    # And User pilih dropdown Jenis Kelamin
    # And User pilih dropdown Tanggal Lahir
    # And User checklist checkbox promosi Optik Melawai
    # And User tekan button "daftar"
    # Then Registrasi user berhasil


