*** Variables ***
#----- REGISTRATION -----#
${field_fullName-web}    M Tito Ramadhan
${field_phoneNumber-web}    82214633070
${email-web}    tito

#----- ENDPOINT API -----#
${baseURL}    https://gherkin-pilot.stagingapps.net/api

#---- CONFIG BROWSER ----#
#Config Path Extension for Capctha
${extension_captcha}    C:/Users/titor/OneDrive/Documents/WGS-LeadQA/LearnRobot/gherkinpilotproject/pilotprojectWebsite/utility/extensions/mpbjkejclgfgadiemmefgebjfooflfhl/3.1.0_0