*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../stepDefinition/nativeDev/registration/sd_10_succesful_ActivationOTP_viaEmail.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-18T14:24:31.367004_

*** Test Cases ***
Successful Activation OTP via Email
    [Tags]    valid
    Background
    Given I am on the Input OTP form
    When I fill in valid OTP Number
    Then I should see Address Information form

*** Keywords ***
Background
    Given I was input valid data on first page in registration form
    And I click button Lanjutkan to see OTP verification Form