*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../../platformAndroid/stepDefinition/nativeDev/registration/sd_13_successful_addressConfirmation.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-21T23:43:32.020232_

*** Test Cases ***
Successful Address Confirmation
    [Tags]    valid
    Background
    Given the page is showing Address Information form
    When I choose valid data in dropdown field Kota/Kabupaten
    And I choose valid data in dropdown field Kecamatan
    And I should see activated button "Lanjutkan"
    And I Click button "Lanjutkan"
    Then I should see Create Password form

*** Keywords ***
Background
    Given I was input valid data on first page and otp in registration form


