*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../../platformAndroid/stepDefinition/nativeDev/registration/sd_14_successful_createPassword.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-24T15:49:50.961908_

*** Test Cases ***
Successful Create password
    [Tags]    valid
    [Template]    Scenario Outline Successful Create password
    P@ssw0rd    P@ssw0rd

*** Keywords ***
Background
    Given I was input valid data until Address confirmation page, and click "lanjutkan" button

Scenario Outline Successful Create password
    [Arguments]    ${password}    ${confirm_pswd}
    Background
    Given the page is showing Create Password form
    When I fill valid data in "Password" field "${password}"
    And I fill valid data in "Ulangi Password" field "${confirm_pswd}"
    And I should see activated button "Lanjutkan" in page create password
    And I click button "Lanjutkan" in page create password
    Then I should see message: "Apakah anda yakin telah mengisi data dengan benar?"


