*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../stepDefinition/nativeDev/registration/sd_21_unsuccessful_createPassword.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-28T11:32:28.576721_

*** Test Cases ***
Unsuccessful Create password
    [Tags]    valid
    [Template]    Scenario Outline Unsuccessful Create password
    password    password    Validasi1
    P@ssw0rd    p@ssw0rD    Validasi2


*** Keywords ***
Background
    Given I was succesfully see Create password form

Scenario Outline Unsuccessful Create password
    [Arguments]    ${password}    ${confirm_pswd}    ${err_msg}
    Background
    Given the page is showing Create Password form again
    When I fill invalid data in "Password" field "${password}"
    And I fill invalid data in "Ulangi Password" field "${confirm_pswd}"
    And I should see activated button "Lanjutkan" in form
    And I click button "Lanjutkan" in form
    Then I should see error message notification "${err_msg}"


