*** Settings ***
Documentation    
Test Tags    PilotProject-Mobile-Registration
Resource    ../../../stepDefinition/nativeDev/registration/sd_3_valid_registerAccount.resource
Resource    ../../../utility/globalKeyword.resource
Resource    ../../../utility/variable.resource
Metadata    Feature    Mobile Registration
Metadata    Generated by    _gherkin2robotframework on 2025-01-14T16:50:46.742941_

*** Test Cases ***
Valid Register account
    [Tags]    valid
    [Template]    Scenario Outline Valid Register account
    M Tito Ramadhan    titoqa@yopmail.com    ${perorangan}  
    Aku    t@mail.com    ${badanUsaha}    


*** Keywords ***
Background
    Given User membuka aplikasi GherkinPilot Native

Scenario Outline Valid Register account
    [Arguments]    ${nama_lengkap}    ${email}    ${tipe_akun}
    Background
    Given the page is showing Sign Up form
    When I fill valid data Nama Lengkap "${nama_lengkap}"
    And I fill valid Email "${email}"
    And I choose Tipe Akun "${tipe_akun}"
    And I tap agree of term of condition
    And I should see activated button "Lanjutkan"
    And I tap button "Lanjutkan"
    Then I should see OTP Verification form


