*** Settings ***
Documentation    
Resource    ../stepDefinition/sd_addnewFeature.resource
Resource    ../stepDefinition/sd_tmLoginValid.robot
Metadata    Feature    Add new features
Metadata    Generated by    _gherkin2robotframework on 2025-01-12T23:33:45.353528_

*** Test Cases ***
Add new features
    [Template]    Scenario Outline 
    Register    //ul[@class='multiselect-container dropdown-menu show']/li[2]//label[@class='checkbox']    Detail 1
    Login    //ul[@class='multiselect-container dropdown-menu show']/li[4]//label[@class='checkbox']    Detail 2


*** Keywords ***
Background
    Given User already logged in to TM Digital

Scenario Outline 
    [Arguments]    ${featureName}    ${QAAssigned}    ${featureDetail}
    Background
    Given User already open project detail
    When User click button Add New features
    And User Input Fitur "${featureName}"
    And User select tester "${QAAssigned}"   
    And User Input feature detail "${featureDetail}"
    # And User Click button Save
    # And User click button Save on pop up confirmation
    # And User click button OK on pop up information
    # Then Feature successfully added


