*** Settings ***
Force Tags    LoginTMDigital
Resource    ../stepDefinition/sd_tmLoginValid.robot
Metadata    Feature    TM Digital Login
Metadata    Generated by    _gherkin2robotframework on 2024-12-27T20:31:56.771039_

*** Test Cases ***
Login dengan data valid
    [Tags]    valid
    [Template]    Scenario Outline Login dengan data valid
    superadmin@gmail.com    superadmin
    titoqa@maildrop.cc    P@ssw0rd
    bootcampqa@yopmail.com    password


*** Keywords ***
Scenario Outline Login dengan data valid
    [Arguments]    ${email}    ${password}
    Given User berada dihalaman login TM Digital
    When User input alamat email "${email}"
    And User input password "${password}"
    And User klik button "Sign In"
    Then User sukses melakukan login dengan redirect ke halaman dashboard TM Digital


