*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2025-01-01T23:47:35.222354_
Library    Collections
Library    AppiumLibrary

*** Keywords ***
User tap button masuk
    Click Element    //android.widget.Button[@content-desc="MASUK"]
    Sleep    1s

User berada pada halaman login
    Wait Until Element Is Visible    //android.view.View[@content-desc="Selamat datang kembali!"]
    Sleep    1s

User input nomor telepon atau email "${username}"
    ${locator}    Set Variable    android=new UiSelector().className("android.widget.EditText").instance(0)
    Wait Until Element Is Visible    ${locator}
    Click Element    ${locator}
    Input Text    ${locator}    ${username}   
    Sleep    1s

User input kata sandi "${password}"
    ${locator}    Set Variable    android=new UiSelector().className("android.widget.EditText").instance(1)
    Wait Until Element Is Visible    ${locator}
    Click Element    ${locator}
    Input Password    ${locator}    ${password}
    Sleep    1s

User tap button masuk di halaman login
    Click Element    //android.widget.Button[@content-desc="MASUK"]

User masuk ke homepage aplikasi melawai
    Wait Until Element Is Visible    android=new UiSelector().className("android.widget.ImageView").instance(1)
    Click Element    android=new UiSelector().className("android.widget.ImageView").instance(1)
    Sleep    1s

User dapat melihat halaman profile
    Wait Until Element Is Visible    android=new UiSelector().description("Profile\nTab 3 dari 5")
    Click Element    android=new UiSelector().description("Profile\nTab 3 dari 5")
    Sleep    1s
    Element Should Be Visible    //android.view.View[@content-desc="Selamat datang\nMUHAMMAD TITO RAMADHAN"]
    Sleep    1s

