*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2024-12-28T17:55:15.093751_
Library    Collections
Library    AppiumLibrary

*** Keywords ***
User berada pada home device
    Open Application    127.0.0.1:4723
    ...    platformName=Android
    ...    platfromVersion=8.1
    ...    deviceName=2bbbd23d9805
    ...    app=C:\\Users\\titor\\Downloads\\opmre-staging.apk    
    ...    automationName=UiAutomator2

User tap icon melawai aplikasi
    Wait Until Page Contains Element    //android.widget.Button[@content-desc="INGATKAN SAYA NANTI"]
    Click Element    //android.widget.Button[@content-desc="INGATKAN SAYA NANTI"]
    Sleep    1s

Aplikasi melawai sukses terbuka
    Element Should Be Visible    //android.view.View[@content-desc="Selamat datang di Optik Melawai"]

# -------------FOR BACKGROUND----------------#
User membuka aplikasi Melawai
    User berada pada home device
    User tap icon melawai aplikasi
    Aplikasi melawai sukses terbuka


