*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2025-01-03T23:32:19.354474_
Library    Collections
Library    AppiumLibrary
Library    String
Library    Process

*** Keywords ***
User berada pada halaman daftar akun Optik Melawai
    Wait Until Element Is Visible    //android.widget.Button[@content-desc="DAFTAR"]
    Click Element    //android.widget.Button[@content-desc="DAFTAR"]
    Element Should Be Visible    android=new UiSelector().description("Daftar Akun Optik Melawai")
    Sleep    1s

User input field nomor telepon "${telepon}"
   Wait Until Element Is Visible    android=new UiSelector().className("android.widget.EditText")
   Input Text    android=new UiSelector().className("android.widget.EditText")    ${telepon}
   Sleep    1s

User tekan button "lanjutkan"
   Click Element    android=new UiSelector().description("LANJUTKAN")
   Sleep    1s


User input field OTP validasi Nomor Telepon
    Wait Until Element Is Visible    //android.view.View[@content-desc="Validasi Nomor Telepon"]
    Click Element    //android.view.View[@content-desc="http log"]
    Wait Until Element Is Visible    //android.view.View[contains(@content-desc,'https://apistaging.optikmelawai.com/api/v2/auth/register/verify/phone/request')]
    Click Element   //android.view.View[contains(@content-desc,'https://apistaging.optikmelawai.com/api/v2/auth/register/verify/phone/request')]
    Wait Until Page Contains Element     //android.view.View[contains(@content-desc,'Response')]
    Click Element    //android.view.View[contains(@content-desc,'Response')]
    Wait Until Page Contains Element     //android.view.View[contains(@content-desc,'data:{...}')]
    Click Element    //android.view.View[contains(@content-desc,'data:{...}')]
    Wait Until Page Contains Element     //android.view.View[contains(@content-desc,'credential:')]
    ${otp}    Get Element Attribute    //android.view.View[contains(@content-desc,'credential:')]    content-desc
    Sleep    1s
    ${otp}    Get Substring    ${otp}    11    15
    Log To Console    ${otp}
    Wait Until Page Contains Element     //android.widget.Button[@content-desc="Kembali\nKembali"]
    Click Element    //android.widget.Button[@content-desc="Kembali\nKembali"]
    Wait Until Page Contains Element     //android.widget.Button[@content-desc="Kembali\nKembali"]
    Click Element    //android.widget.Button[@content-desc="Kembali\nKembali"]
    Wait Until Element Is Visible    //android.view.View[@content-desc="-\n-\n-"]
    Click Element    xpath=//android.widget.EditText
    
    Close Application

# User tekan button "selesai dan lanjutkan"
#     Click Element    //android.widget.Button[@content-desc="SELESAI DAN LANJUTKAN"]
#     Sleep    1s

User input field alamat email "${email}"
    Fail    Keyword "User input field alamat email "${email}"" Not Implemented Yet

User tekan kembali button "lanjutkan"
    Fail    Keyword "User tekan kembali button "lanjutkan"" Not Implemented Yet

User input field OTP validasi Alamat Email
    Fail    Keyword "User input field OTP validasi Alamat Email" Not Implemented Yet

User tekan kembali button "selesai dan lanjutkan"
    Fail    Keyword "User tekan kembali button "selesai dan lanjutkan"" Not Implemented Yet

User input field kata sandi "${password}"
    Fail    Keyword "User input field kata sandi "${password}"" Not Implemented Yet

User input field alamat "${alamat}"
    Fail    Keyword "User input field alamat "${alamat}"" Not Implemented Yet

User pilih dropdown Provinsi
    Fail    Keyword "User pilih dropdown Provinsi" Not Implemented Yet

User pilih dropdown Kota
    Fail    Keyword "User pilih dropdown Kota" Not Implemented Yet

User pilih dropdown Titel
    Fail    Keyword "User pilih dropdown Titel" Not Implemented Yet

User input field Nama Lengkap "${nama_lengkap}"
    Fail    Keyword "User input field Nama Lengkap "${nama_lengkap}"" Not Implemented Yet

User pilih dropdown Jenis Kelamin
    Fail    Keyword "User pilih dropdown Jenis Kelamin" Not Implemented Yet

User pilih dropdown Tanggal Lahir
    Fail    Keyword "User pilih dropdown Tanggal Lahir" Not Implemented Yet

User checklist checkbox promosi Optik Melawai
    Fail    Keyword "User checklist checkbox promosi Optik Melawai" Not Implemented Yet

User tekan button "daftar"
    Fail    Keyword "User tekan button "daftar"" Not Implemented Yet

Registrasi user berhasil
    Fail    Keyword "Registrasi user berhasil" Not Implemented Yet

