*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2024-12-28T17:55:15.093751_
Library    Collections
Library    AppiumLibrary

*** Keywords ***
User masuk kedalam aplikasi
    Open Application    127.0.0.1:4723
    ...    platformName=Android
    ...    platfromVersion=8.1
    ...    deviceName=2bbbd23d9805
    ...    app=C:\\Users\\titor\\Downloads\\app-debug.apk    
    ...    automationName=UiAutomator2
Input field username
    Wait Until Element Is Visible    android=new UiSelector().className("android.view.View").instance(2)
    Click Element    android=new UiSelector().className("android.view.View").instance(2)
    Input Text    //android.widget.EditText    tito
    Sleep    1s
Tap button login
    Click Element    //android.widget.Button
    Sleep    1s
    