*** Settings ***
Documentation    
Resource    ../../stepDefinition/dashboard-affiliate/sd_signupAffiliator.resource
Metadata    Feature    Signup Affiliator
Metadata    Generated by    _gherkin2robotframework on 2026-01-13T14:58:03.853169_

*** Test Cases ***
#Positif Case
Signup Affiliator dengan data valid
    [Tags]    positifCase
    [Template]    Scenario Outline Signup Affiliator dengan data valid
    titoqa2@yopmail.com    Tito QA    titoqa2    81573313198    P@ssw0rd    P@ssw0rd

*** Keywords ***
Background
    Given User telah membuka website pagii affiliate
    And User klik tombol "SignUp now" pada halaman Sign In pagii affiliate

Scenario Outline Signup Affiliator dengan data valid
    [Arguments]    ${email}    ${fullName}    ${userName}    ${phoneNumber}    ${password}    ${confirmPassword}
    Background
    Given User berada pada halaman Sign Up pagii affiliate
    When User input field Email Address "${email}"
    And User input field Full Name "${fullName}"
    And User input field Username "${userName}"
    And User input field Phone Number "${phoneNumber}"
    And User input field Password "${password}"
    And User input field Confirm Password "${confirmPassword}"
    And User klik button Sign Up
    Then User berhasil melakukan registrasi sebagai affiliator
    And redirect ke halaman Login Affiliator